default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: api_development

test:
  <<: *default
  database: api_test

production:
  <<: *default
  database: api_production
  password: <%= ENV['DATABASE_PASSWORD'] || 'postgres' %>
  host:     <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] || 'localhost' %>
  port:     <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] || '5432' %>