# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 838bc9cf20d8a3fa2b798ac7644891a341cf6c534bd59ee4aec0db82ea5a0f3207e203c70b8233a6ef1b904fb92949436258cbfe24a909c8a51de74a98cd0951

test:
  secret_key_base: 8154c3b5c86402edc839ce521443612b622bfa6b47a21345454668c861cc307ab19c55f6e9c191eaf89c03ed39ca31d47cce180ae26f1d7ff2dfd3e60616f733

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || '8154c3b5c86402edc839ce521443612b622bfa6b47a21345454668c861cc307ab19c55f6e9c191eaf89c03ed39ca31d47cce180ae26f1d7ff2dfd3e60616f733' %>
